### PR TITLE
Add auth.oidc.preferredJwsalgorithm param

### PR DESCRIPTION
**Pull request by happy-code-com**
#### Which issue this PR fixes
* Added templating "nifi.security.user.oidc.preferred.jwsalgorithm" property as "auth.oidc.preferredJwsalgorithm" value

#### Checklist

- [ ] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by banzo — APPROVED** [review]

**Comment by happy-code-com** [comment]
I will try to figure out what the problem is with the tests and make corrections.

**Comment by banzo** [comment]
It might just be limits on container pulls or resources that GitHub enforces.

**Comment by banzo** [comment]
nope, the OIDC tests seem to be broken.
If you have an idea on how to fix them, you are more welcome to share it :)

**Comment by happy-code-com** [comment]
Hmm. interestingly, in fact nothing was added, just an empty string started to be passed from the parameters... I'll try to think what could be the matter 🤯

**Comment by wknickless** [comment]
Looks like we may be running into https://github.com/puppeteer/puppeteer/issues/10398 .

**Comment by banzo** [comment]
closing so that reopening will retrigger all the checks

**Review by banzo — APPROVED** [review]

**Pull request merged**
