### PR TITLE
Restore safetyValve and singleUser when not using LDAP or OIDC

### LINKED ISSUE #208: [cetic/nifi] nifi property settings broken if not using LDAP or OIDC
**Describe the bug**

NiFi properties cannot be set unless LDAP or OIDC is turned on.

**Version of Helm, Kubernetes and the Nifi chart**:

First appears in chart version 1.0.2 with pull request #169.

**What you expected to happen**:

Using this values setting:

```
properties:
  safetyValve:
    nifi.content.claim.max.appendable.size: "1 B"
```
...would result in NiFi being configured with that property set.

**What happened**:

The statefulset and (and therefore pods) had no command: stanza whatsoever, so the NiFi property was not set.

**How to reproduce it** (as minimally and precisely as possible):

Use the above values.yaml and observe that the server container in the pods do not have a command: stanza, and that NiFi does not end up configured per that setting.

**Anything else we need to know**:

Commit 0867843cd39d6d1bf4a329969e6956942167589e in templates/statefulset.yaml line 121 disables the command: stanza in the server container.

### LINKED ISSUE #211: Persistent volumes not used when LDAP or OIDC are enabled
Hello folks,

I would like to educate myself here on why persistent volumes like `data, auth-conf, config-data, flowfile-repository` etc are not mounted (volumeMounts) when `ldap` or `oidc` are not enabled. See `statefulset.yaml` snippet below.

```
{{- if or (.Values.auth.ldap.enabled) (.Values.auth.oidc.enabled) }}
          - name: "data"
            mountPath: /opt/nifi/data
          - name: "auth-conf"
            mountPath: /opt/nifi/nifi-current/auth-conf/
          - name: "config-data"
            mountPath: /opt/nifi/nifi-current/config-data
          - name: "flowfile-repository"
            mountPath: /opt/nifi/flowfile_repository
          - name: "content-repository"
            mountPath: /opt/nifi/content_repository
          - name: "provenance-repository"
            mountPath: /opt/nifi/provenance_repository
          - name: "bootstrap-conf"
            mountPath: /opt/nifi/nifi-current/conf/bootstrap.conf
            subPath: "bootstrap.conf"
          - name: "nifi-properties"
            mountPath: /opt/nifi/nifi-current/conf/nifi.temp
            subPath: "nifi.temp"
          - name: "authorizers-temp"
            mountPath: /opt/nifi/nifi-current/conf/authorizers.temp
            subPath: "authorizers.temp"
          - name: "authorizers-empty"
            mountPath: /opt/nifi/nifi-current/conf/authorizers.empty
            subPath: "authorizers.empty"
          - name: "bootstrap-notification-services-xml"
            mountPath: /opt/nifi/nifi-current/conf/bootstrap-notification-services.xml
            subPath: "bootstrap-notification-services.xml"
          - name: "login-identity-providers-xml"
            mountPath: /opt/nifi/nifi-current/conf/login-identity-providers.xml
            subPath: "login-identity-providers.xml"
          - name: "state-management-xml"
            mountPath: /opt/nifi/nifi-current/conf/state-management.xml
            subPath: "state-management.xml"
          - name: "zookeeper-properties"
            mountPath: /opt/nifi/nifi-current/conf/zookeeper.properties
            subPath: "zookeeper.properties"
          - name: "flow-content"
            mountPath: /opt/nifi/data/flow.xml
            subPath: "flow.xml"
          {{- range $secret := .Values.secrets }}
            {{- if $secret.mountPath }}
              {{- if $secret.keys }}
                {{- range $key := $secret.keys }}
          - name: {{ include "apache-nifi.fullname" $ }}-{{ $secret.name }}
            mountPath: {{ $secret.mountPath }}/{{ $key }}
            subPath: {{ $key }}
            readOnly: true
                {{- end }}
              {{- else }}
          - name: {{ include "apache-nifi.fullname" $ }}-{{ $secret.name }}
            mountPath: {{ $secret.mountPath }}
            readOnly: true
              {{- end }}
            {{- end }}
          {{- end }}
          {{- range $configmap := .Values.configmaps }}
            {{- if $configmap.mountPath }}
              {{- if $configmap.keys }}
                {{- range $key := $configmap.keys }}
          - name: {{ include "apache-nifi.fullname" $ }}-{{ $configmap.name }}
            mountPath: {{ $configmap.mountPath }}/{{ $key }}
            subPath: {{ $key }}
            readOnly: true
                {{- end }}
              {{- else }}
          - name: {{ include "apache-nifi.fullname" $ }}-{{ $configmap.name }}
            mountPath: {{ $configmap.mountPath }}
            readOnly: true
              {{- end }}
            {{- end }}
          {{- end }}
          {{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 10 }}
          {{- end }}
{{- end }}
```

But volumes are attached when `persistence.enabled` is `true`.

```
{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: logs
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.logStorage.size }}
    - metadata:
        name: "config-data"
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.configStorage.size }}
    - metadata:
        name: data
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.dataStorage.size }}
    - metadata:
        name: flowfile-repository
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.flowfileRepoStorage.size }}
    - metadata:
        name: content-repository
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.contentRepoStorage.size }}
    - metadata:
        name: provenance-repository
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.provenanceRepoStorage.size }}
    - metadata:
        name: auth-conf
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.authconfStorage.size }}
{{- end }}
```

I am really confused here. Any help would be appreciated.

Versions:
Nifi: 1.14.0
Helm chart: 1.0.3

### LINKED ISSUE #213: [cetic/nifi] NOTES.txt assumes LoadBalancer, not default ClusterIP Service
**Describe the bug**
templates/NOTES.txt describes how to find the public IP address of the NiFi UI, assuming it is using a LoadBalancer service.  But the default values.yaml file sets up a ClusterIP service.

**Version of Helm, Kubernetes and the Nifi chart**:

Helm 3, Kubernetes v1.20.2, chart v1.0.2

**What happened**:

The output of a successful ```helm install``` prints out instructions for finding the IP address of the NiFi UI as if the UI service is a ClusterIP.

**What you expected to happen**:

The output of a successful ```helm install``` should print out instructions for using ``kubectl port-forward`` to access the NiFi UI.

**How to reproduce it** (as minimally and precisely as possible):

```helm install nifi nifi```

### PR DESCRIPTION
**Pull request by wknickless**
#### What this PR does / why we need it:
Fixes the NiFi Helm chart when LDAP and OIDC are not enabled, which they are not by default.  

#### Which issue this PR fixes
  - fixes #208
  - fixes #211 
  - fixes #213 

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Fix NOTES.txt suitable for the default ClusterIP service
- [x] Add test to confirm persistent storage works (with possible fixes)
- [x] Add test to confirm LDAP works (with possible fixes)
- [x] Add test to confirm OIDC works (with possible fixes)
- [x] Adjust github workflow definition to run in master branch too
- [x] Chart Version bumped

### CODE REVIEW

**Comment by wknickless** [comment]
@banzo @zakaria2905 I have not yet tested whether this breaks LDAP and OIDC, or whether it actually fixes persistent storage, so you might want to hold off on merging this until you get a chance to test it or I get those tests merged.

**Comment by leshibily** [comment]
@banzo can we expect the release this week?

**Comment by banzo** [comment]
@wknickless amazing work with the tests, thank you very much!

@leshibily probably not, the oidc feature still need to be tested and we will not have time to take care of it this week.

**Comment by leshibily** [comment]
@banzo thank you.

@wknickless forgot to mention, great work, mate.

**Comment by wknickless** [comment]
Thanks for the positive feedback!

Didn't get the OIDC test written today.  As of 971dea20159b58fc65ebde2f74492e84a481feaf OIDC works.  I tested it manually, driving Firefox, using Keycloak as the OpenID Provider.  The Keycloak setup artifacts are in the tests/ directory.  

Looks like it should be straightforward to write a simple login-succeeds and login-fails test pair in Puppeteer driving [browserless](https://docs.browserless.io/docs/start.html), but I guess I'll find out shortly.

**Comment by wknickless** [comment]
@banzo This PR passes the tests and resolves #208, #211 and #213.  But @leshibily is probably correct that it won't support scaling beyond a single node.

How would you like to proceed?  If you merge and release as-is then people can use it for single NiFi node clusters.  Alternatively, we could open another issue about scaling to multiple nodes and update the scope of this PR.

Also, would you entertain a dependency on [cert-manager](https://cert-manager.io/docs/) to manage the TLS keys within the NiFi cluster when scaling beyond a single node, and for the UI?  Or would you prefer to stick with the NiFi toolkit?

**Comment by leshibily** [comment]
@wknickless Thank you for the quick fixes and thanks for verifying the bug. Why isn't a Nifi cluster created  even though `properties.isNode` is set to `true` in the `values.yaml` file?
Also, how long would it take to fix the clustering issue? This is a blocker for us using Nifi in production.

Appreciate the efforts again.

**Comment by banzo** [comment]
@wknickless 

> How would you like to proceed? If you merge and release as-is then people can use it for single NiFi node clusters. Alternatively, we could open another issue about scaling to multiple nodes and update the scope of this PR.

I think we should merge as is, multi-node is broken anyway in the current latest release. And then fix SSL multi-node in another PR.

> Also, would you entertain a dependency on cert-manager to manage the TLS keys within the NiFi cluster when scaling beyond a single node, and for the UI? Or would you prefer to stick with the NiFi toolkit?

cert-manager seems to be a good fit to handle that issue. We are trying it for Nifi UI in some deployments.

**Comment by wknickless** [comment]
@banzo Thank you for the guidance.  I've opened #218 for the cert-manager feature that will also allow secure clusters.

**Pull request merged**
