### PR TITLE
Add TLS support

### PR DESCRIPTION
**Pull request by makeacode**
#### What this PR does / why we need it:
Add TLS support to the chart....heavily based on example/knowledge from https://github.com/sushilkm/nifi-chart.git.  This is likely a very rough first draft but seems to work for me.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by goof03** [comment]
Hi!
I try your Pull request and it's seems to work …

I just add : 

- name: auth-conf
        emptyDir: {}

to volumes to get it working with persistence = false
But it's ok now …

My last bug is exatly the same as this one : 
https://github.com/sushilkm/nifi-chart/issues/1
https://issues.apache.org/jira/browse/NIFI-7767

I have try to downgrade (even if it's already the 1.11.4) but nothing change
My subjectAltNames: [] is desperatly empty

Do you have an idea please ?

Thanks anyway it's a good job … :-)

**Comment by makeacode** [comment]
Thanks for catching that volume...guess I should have tested a non-secure cluster as well.  I'll get it added to the PR.

**Comment by goof03** [comment]
And for the :
javax.net.ssl.SSLPeerUnverifiedException: Hostname nifi-0.nifi-headless.nifi.svc.cluster.local not verified ... DN: CN=nifi-0.nifi-headless.nifi.svc.cluster.local, OU=NIFI subjectAltNames: []

Do you have an idea i stuck with that …

**Comment by goof03** [comment]
wahoo !!!! thanks everything is working now … Why i havent see the nifi-toolkit image tag myself … :-/

**Comment by sushilkm** [comment]
The bug you have referred https://issues.apache.org/jira/browse/NIFI-7767 is being fixed in 1.12.1 you should be able to use that one when released.

**Comment by sushilkm** [comment]
@goof03 The bug you have referred https://issues.apache.org/jira/browse/NIFI-7767 is being fixed in 1.12.1 you should be able to use that one when released.

Use image tag 1.11.4 until 1.12.1 is released for both nifi and niffi-toolkit

**Comment by sushilkm** [comment]
I am happy to see that my work is helping you guys to proceed further here in this repository.
I would feel great if you can add credit reference to my chart in the README and license sections.

**Comment by sushilkm** [comment]
Thanks @makeacode for adding the credit 👍

**Comment by makeacode** [comment]
@sushilkm no problem....you did the work....i just merged it in and tweaked it a bit

**Comment by alexnuttinck** [comment]
Hey @makeacode, @sushilkm  and @goof03. Thanks you all for the incredible work made here! I'm quite busy for the moment, but I will try to review this PR and merge it asap :)

**Comment by alexnuttinck** [comment]
> I am happy to see that my work is helping you guys to proceed further here in this repository.
> I would feel great if you can add credit reference to my chart in the README and license sections.

Just normal! I will see also to add a contributor sections in the README :) Maybe by using https://github.com/all-contributors/all-contributors or reusing https://github.com/cetic/helm-nifi/graphs/contributors

**Comment by makeacode** [comment]
This is the values.yaml i've been working with:

```yaml
replicaCount: 2

properties:
  webProxyHost: nifi.<domain>.com
  clusterSecure: true
  httpPort: ""
  httpsPort: 8443

persistence:
  enabled: true

service:
  type: LoadBalancer
  httpsPort: 443
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  # sessionAffinity: ClientIP
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 600
      
ca:
  enabled: true
  persistence:
    enabled: true

auth:
  admin: me@<domain>.com

  oidc:
    enabled: true
    discoveryUrl: https://adfs.<domain>.com/adfs/.well-known/openid-configuration
    clientId: <omitted>
    clientSecret: <omitted>
    claimIdentifyingUser: upn
```

note that the certificates generated on the nodes by the CA container don't currently "give" you the admin certificate that's generated (essentially it's stuck inside the container).  I don't know how to get that exposed since it's generated at runtime...and i'm not sure how to easily get your browser to send it even if you did have it.   that's the reason i worked on getting oidc working as well...so I didn't have to authenticate using a certificate.

**Comment by alexnuttinck** [comment]
Ok thanks @makeacode!

> note that the certificates generated on the nodes by the CA container don't currently "give" you the admin certificate that's generated (essentially it's stuck inside the container). I don't know how to get that exposed since it's generated at runtime...and i'm not sure how to easily get your browser to send it even if you did have it. that's the reason i worked on getting oidc working as well...so I didn't have to authenticate using a certificate.

Make sense.

Let's merge, I will look at my securityContext problem afterwards.

Thank you all :)

**Pull request merged**
