### PR TITLE
bug/fix term sidecars

### LINKED ISSUE #158: [cetic/nifi] cannot gracefully shutdown because of busybox sidecar
Because of node offloading, I need to set a larger `terminationGracePeriodSeconds` to allow for file transfer time.

But, because of that, it becomes apparent that the busybox sidecars are preventing a graceful shutdown.

TO REPRODUCE:
```shell
# Will generate a pod spec like the used in the chart
kubectl run busybox --image=busybox --restart=Never -- tail -n+1 -F /dev/random

#confirm that args is created in the same way as the template.
kb get pod busybox -o jsonpath="{.spec.containers[0].args}"
# OUTPUT: 
# ["tail","-n+1","-F","/dev/random"]

# wait for pod ready
kubectl wait --for=condition=ready pod/busybox

# forceful shutdown (will take 30+ seconds, or some 
# seconds + the cluster's default `terminationGracePeriodSeconds`)
time kubectl delete pod busybox
# OUTPUT:
# kubectl delete pod busybox  0,09s user 0,04s system 0% cpu 39,483 total
```

Now compare this to a container correctly handling SIGTERM:
```shell
kubectl run nginx --image=nginx --restart=Never

# wait for pod ready
kubectl wait --for=condition=ready pod/nginx

# graceful shutdown (will take ~5 seconds, the time it takes for 
# kubectl to get the information of its immediate death)
time kubectl delete pod nginx
# OUTPUT:
# kubectl delete pod nginx  0,10s user 0,03s system 2% cpu 5,597 total
```

EXPECTED:
Quick termination. Busybox catches SIGTERM and the tail process is terminated immediately.

SOLUTION:
Couldn't find a way to make this a oneline. Probably an entryproint script for log tailing will be needed.

NOTE:
This is not a big problem if you use a small `terminationGracePeriodSeconds` as the busybox sidecars will be killed in 30 seconds or so. But if you use a `terminationGracePeriodSeconds=300` like me, it makes node maintenance a pain in the ass.

Hope this is useful.

Thanks for this great chart!

### LINKED ISSUE #239: [cetic/nifi] pod stops only after terminationGracePeriodSeconds exceeded
**Describe the bug**
When a pod in a cluster is triggered to stop, the offload node process can take some time to complete.  Increasing the terminationGracePeriodSeconds to 600 provides enough time for the server container to complete offloading with a generous buffer (in my environment).  While the Nifi server container does stop, the sidecar containers continue to run.  The result is the pod does not terminate until the terminationGracePeriodSeconds passes.

**Version of Helm, Kubernetes and the Nifi chart**:
Helm: 3.5.1
Kubernetes: 1.20.5
Nifi chart: 1.0.5

**What happened**:
See description.

**What you expected to happen**:
The termination of the pod should complete when the Nifi server container stops.  The terminationGracePeriodSeconds should be a last resort to terminate the pod.

**How to reproduce it** (as minimally and precisely as possible):
Deploy a Nifi cluster with terminationGracePeriodSeconds to 600.  Reduce the number of nodes in the cluster and note the time.  Monitor the Nifi server container log to ensure offload processes complete.  Monitor how long it takes for the pod to terminate.

**Anything else we need to know**:
None

### PR DESCRIPTION
**Pull request by gforeman02**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #239
  - fixes #158 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by gforeman02** [comment]
@banzo @zakaria2905 @alexnuttinck @AyadiAmen the github checks are not running predictably.  i submitted empty commits for this PR to re-trigger them and eventually they all passed.

**Comment by wknickless** [comment]
@gforeman02 hopefully https://github.com/cetic/helm-nifi/pull/218/commits/eb22003a1a2ee59185935cb626bcb588678475bb makes at least one of the tests more reliable.

Speaking of tests, do you have any thoughts about how to write them to ensure this problem stays fixed?

**Comment by gforeman02** [comment]
@wknickless the original tests do complete after several attempts.  The tests all have the timeouts specified.  Is it possible that the [after block](https://github.com/cetic/helm-nifi/blob/3ae6387a0d98d4c6e48be692e3fd82a8e55de34d/tests/04-oidc-login-test.js#L40) is just timing out?  All I see from the final output of the test is a boolean indication.  Tests that fail have `false` returned.  Also not sure if the `--timeout` parameter is recognized by the `before` or `after` calls.

**Comment by wknickless** [comment]
@gforeman02 The old test used a Kubernetes Job to run the mocha script, sat in a kubectl loop waiting for the Job to terminate, and then checked whether the Job completion status was equal to "succeeded".  My understanding is that the status of a Job is "succeeded" if the process inside terminates normally.  But there may have been a race condition or something else that I wasn't taking into account.  The new test sets up puppeteer, chai and mocha in the runner VM directly and doesn't depend on the behavior of a Kubernetes Job, so it should more reliably reflect the result of the mocha script.

**Comment by wknickless** [comment]
@gforeman02 Sorry - my question wasn't clear - do you have any thoughts about how we could write a test to ensure the sidecars terminate cleanly?  I have scars that itch whenever I fix a code problem and don't write a test to ensure it stays fixed.  :-)

**Comment by wknickless** [comment]
@gforeman02 How would you feel about eliminating those sidecars altogether, in favor of teaching NiFi to log everything to the stdout/stderr of its pod?

I figured out how to do that while working on the NiFi Registry chart: https://github.com/wknickless/dysnix-charts/blob/a78f55316d3cc8acaecd4659c6e0717f4e8df17c/dysnix/nifi-registry/templates/statefulset.yaml#L193

**Comment by gforeman02** [comment]
@wknickless at this point, if this fix works, would like to get it deployed so all can take advantage of the fix.  It seems like a significant change in the way the chart operates so maybe appropriate to a major release at this point.  Just my thoughts though.

**Comment by wknickless** [comment]
@gforeman02 I worked pretty hard to keep my helm-nifi changes backward-compatible, including writing tests to prove that they were in fact not breaking things from prior versions (e.g. LDAP authentication).  And to be clear, I didn't make the logging change in helm-nifi.  So I'm not sure it's a major version bump, but I'm quite comfortable with a minor version bump.

In the dysnix/nifi-registry chart, the logging was performed by a background tail -f in the nifi-registry container.  When I had the server log directly to stdout/stderr the logging information still went to stdout/stderr in the nifi-registry container.  So from the user's perspective that behavior dysnix/nifi-registry chart user interface didn't change.

That being said, in dysnix/nifi-registry I did change the hierarchy of some of the values.yaml variables.  Depending on the review performed by and feedback by @dennybaa , I might put in some templating to avoid having to bump the major version, or go ahead and bump the major version because the user interface changes a bit.

**Review by dennybaa — APPROVED** [review]
lgtm. thank you!

**Comment by gforeman02** [comment]
@banzo you mentioned #218 would be included in a major release.  Is it possible to get #240 and #243 deployed to master and released?

**Comment by banzo** [comment]
> @banzo you mentioned #218 would be included in a major release. Is it possible to get #240 and #243 deployed to master and released?

sure, please bump the chart version to 1.1.1 and fix the small conflicts

**Comment by gforeman02** [comment]
@banzo #240 and #243 conflicts resolved and chart version bumped

**Review by banzo — APPROVED** [review]

**Pull request merged**
