### PR TITLE
removed logback-xml from config to use NiFi default logback.xml

### PR DESCRIPTION
**Pull request by hobe**
**Is your feature request related to a problem? Please describe.**
We'd like to customize the logging and therefore we want to mount a custom logback.xml file. This can be achieved by adding a custom configmap (via values.configmaps):

eg.:
`
configmaps:
  - name: nifi-logback-config
    keys:
      - logback.xml
    mountPath: /opt/nifi/nifi-current/conf
`

Unfortunately there is already a default logback.xml mounted directly within the helm chart which also differs from the default logback.xml which is shipped with nifi (1.12.1)

**Describe the solution you'd like**
Removed the config/logback.xml file and the volume and volumeMounts from the statefulset for the logback.xml to get the default logback.xml which is shipped with NiFi image itself. Then it is possible to overwrite it with a custom file (via configmap in the values) 

**Describe alternatives you've considered**
Other mount options or postStart scripts are not possible because the file is already mounted to conf/logback.xml and is readonly. It is also not possible to use another filepath to logback.xml via nifi.properties

### CODE REVIEW

**Comment by novakov-alexey** [comment]
looking forward for this change 👍 
it will satisfy #68 issue as well

**Comment by hobe** [comment]
@alexnuttinck did you already have time to look into this PR?

**Comment by banzo** [comment]
@hobe he is away this week

**Review by alexnuttinck — APPROVED** [review]

**Comment by alexnuttinck** [comment]
lgtm, sorry for the delay.

**Pull request merged**
