### PR TITLE
add decomissioning when pod is stopped

### PR DESCRIPTION
**Pull request by stoetti**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by alexnuttinck** [comment]
@stoetti Thanks for this PR!

I already move the content of the extraContainer from the values.yaml to the statefulset.
After a quick test, the cluster-shutdown pod goes to the offloaded part:
```
wait until node has state 'OFFLOADED'
```
and does not make the delete.

I will search why asap.

Can you already update the README.md?

**Comment by stoetti** [comment]
Thanks for the work.
I will update the README tomorrow.

**Comment by stoetti** [comment]
> I already move the content of the extraContainer from the values.yaml to the statefulset.
> After a quick test, the cluster-shutdown pod goes to the offloaded part:
> 
> ```
> wait until node has state 'OFFLOADED'
> ```
> 
> and does not make the delete.

How does your test scenario looks like? I just did a quick retest installing the chart with 3 nodes and scale down to 2 nodes, the third node is deleted correctly.
Maybe there is a constellation that is not yet handled by the preStop-script.

**Comment by stoetti** [comment]
@alexnuttinck 
any news on this one?

**Comment by stoetti** [comment]
> But what I do not understand is that when I do it manually from the `cluster-shutdown` container, it works ...
> It is confusing.

It most definitely is ;).


Does this behavior occur upon each run?
Do you use a "fresh" Release without any manual up- or down-scaling using the nifi api?
Did you check the app-log of the nifi-2 container?

**Comment by alexnuttinck** [comment]
> Does this behavior occur upon each run?

Yes, each time.

> Do you use a "fresh" Release without any manual up- or down-scaling using the nifi api?

I tried to make a fresh release and a manual scale-down.

```
helm upgrade nifi . -f values.yaml
# replicaCount 2
```
or
```
kubectl scale statefulsets nifi --replicas=2
```
give me the same result.

> Did you check the app-log of the nifi-2 container?

Nothing unexpected. Logs stop immediately when the node is disconnected.

**Comment by stoetti** [comment]
I finally figured it out.

The problem was that offloading could not be finished cause the node was already offline (k8s did not route any requests). I took a look into the official nifi-dockerfile and updated the command in the chart using 'trap' command for offloading before stopping the node.
Therefore the additional container got obsolete.

Please give it another try in your environment.

**Comment by alexnuttinck** [comment]
Thanks a lot for your work @stoetti ! 
It works like a charm now.

**Pull request merged**
